# Generated by Django 3.2.3 on 2021-05-24 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_delete_newmodel'),
        ('river', '0002_auto_20210521_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('workflow_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='river.workflow')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='count_id', to='polls.company')),
            ],
            options={
                'unique_together': {('company',)},
            },
            bases=('river.workflow',),
        ),
    ]
