# Generated by Django 3.2.3 on 2021-05-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20210521_1223'),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewModel',
        ),
    ]
